# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### RPC and REST configs #####

# RPC endpoint for ethereum chain
eth_rpc_url = "https://goerli.infura.io/v3/<YOUR_INFURA_KEY>"

# RPC endpoint for bsc chain
bsc_rpc_url = "https://data-seed-prebsc-1-s1.binance.org:8545/"

# RPC endpoint for bttc chain
bttc_rpc_url = "http://bttc0:8545"

# RPC endpoint for tendermint
tendermint_rpc_url = "http://0.0.0.0:26657"

# Delivery REST server endpoint
delivery_rest_server = "http://0.0.0.0:1317"

# RPC endpoint for tron
tron_rpc_url = "47.252.19.181:50051"
tron_grid_url = "https://test-tronevent.bt.io"
tron_grid_api_key = "xxxxxxxx"

#### Bridge configs ####

# AMQP endpoint
amqp_url = "amqp://guest:guest@localhost:5672/"

## Poll intervals
checkpoint_poll_interval = "5m0s"
eth_syncer_poll_interval = "1m0s"
bsc_syncer_poll_interval = "10s"
tron_syncer_poll_interval = "3s"
noack_poll_interval = "16m50s"
clerk_poll_interval = "10s"
span_poll_interval = "1m0s"
staking_poll_interval = "1m0s"

#### gas limits ####
main_chain_gas_limit = "5000000"
tron_chain_fee_limit = "1000000000"

#### busy limits ####
eth_unconfirmed_txs_busy_limit = "1000"
bsc_unconfirmed_txs_busy_limit = "1000"
tron_unconfirmed_txs_busy_limit = "20000"

eth_max_query_blocks = "100"
bsc_max_query_blocks = "5"
tron_max_query_blocks = "5"

##### Timeout Config #####
no_ack_wait_time = "30m0s"

